{{- if .Values.components.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "auth") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: auth
      port: 9100
      targetPort: auth
      protocol: TCP
    {{- if .Values.components.auth.masterListen }}
    - name: auth-master
      port: 9102
      targetPort: auth-master
      protocol: TCP
    {{- end }}
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "auth") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-auth-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "auth") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: telemetry
      port: 8080
      targetPort: telemetry
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "auth") | nindent 4 }}
{{- end }}
