{{- if .Values.components.dict.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-dict
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "dict") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: locks
      port: 9107
      targetPort: locks
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "dict") | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "yarilo.fullname" . }}-dict-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yarilo.componentLabels" (dict "root" . "component" "dict") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: telemetry
      port: 8080
      targetPort: telemetry
      protocol: TCP
  selector:
    {{- include "yarilo.componentSelectorLabels" (dict "root" . "component" "dict") | nindent 4 }}
{{- end }}
