apiVersion: v2
name: yarilo
description: Production-grade IMAP/POP3/Submission mail server
type: application

version: 2.3.87
appVersion: "2.3.107"

keywords:
  - imap
  - submission
  - lmtp
  - mail
icon: https://raw.githubusercontent.com/yarilomail/yarilo/main/docs/icon.svg
home: https://github.com/yarilomail/yarilo
sources:
  - https://github.com/yarilomail/yarilo
